resolver: nightly-2020-03-18
packages:
- .
- hie-plugin-api

extra-deps:
# - ./submodules/HaRe

- apply-refact-0.7.0.0
- bytestring-trie-0.2.5.0@sha256:9efa9c6f556314d28486be2470ff789419c5238ed2e354870623a3cbbd28fbe2,3349
# - cabal-helper-1.0.0.0
- github: jneira/cabal-helper
  commit: ffb1f57a5ffc6b7ac3c46a9974c4420a6d2bb9b2
- clock-0.7.2
- constrained-dynamic-0.1.0.0
- floskell-0.10.2
# To avoid build error with ghc-8.8.2
# See https://github.com/haskell/haddock/issues/1123
- git: https://github.com/haskell/haddock.git
  commit: be8b02c4e3cffe7d45b3dad0a0f071d35a274d65
  subdirs:
    - haddock-api
# - haddock-api-2.23.0
- hoogle-5.0.17.15
- hsimport-0.11.0@sha256:e8f1774aff97215d7cc3a6c81635fae75b80af182f732f8fe28d1ed6eb9c7401,3170
- ilist-0.3.1.0
- monad-dijkstra-0.1.1.2
- semigroups-0.18.5
- temporary-1.2.1.1
- unliftio-core-0.2.0.1

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
